[env]
TERM = "alacritty"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { blinking = "On", shape = "Block" }
thickness = 0.15
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true

[font]
normal = { family = "Hack Nerd Font", style = "Regular"}
size = 13

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
opacity = 0.98
startup_mode = "Windowed"

[general]
live_config_reload = true

import = [
    #"~/.config/alacritty/themes/catppuccin-latte.toml"
    #"~/.config/alacritty/themes/catppuccin-frappe.toml"
    "~/.config/alacritty/themes/catppuccin-macchiato.toml"
    #"~/.config/alacritty/themes/catppuccin-mocha.toml"
]
